### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by judewoolls** [judewoolls/project-planning-demo#2]
**User Story**

As a community member, I want to read testimonials from previous attendees so that i can feel confident about attending events.

**Acceptance Criteria**

- [ ] The home page or a dedicated testimonials page displays a section with testimonials
- [ ] Each testimonial includes the attendee's name, event attended, and comments.
- [ ] The testimonials section is responsive and looks good on all main device sizes.

**Tasks**

- [ ] Create a HTML section for testimonials
- [ ] Style the testimonials using bootstrap
- [ ] Populate the section with sample testimonials including names, events and comments.
